name: "Enchere-Et-En-Os"
services:
#  api-gateway-api:
#    build:
#      context: ../apps/api/api-gateway
#      dockerfile: ../../../docker/Dockerfile.api
#    environment:
#      DATABASE_URL: postgres://user:password@main-db:5432/main
#      REDIS_HOST: redis
#      NATS_URL: nats://nats:4222
#    depends_on:
#      - main-db
#      - redis
#      - nats
#    ports:
#      - "8000:8000"
#
#  auction-api:
#    build:
#      context: ../apps/api/auction-service
#      dockerfile: ../../../docker/Dockerfile.api
#    environment:
#      DATABASE_URL: postgres://user:password@main-db:5432/main
#      REDIS_HOST: redis
#      NATS_URL: nats://nats:4222
#    depends_on:
#      - main-db
#      - redis
#      - nats
#
#  product-api:
#    build:
#      context: ../apps/api/product-service
#      dockerfile: ../../../docker/Dockerfile.api
#    environment:
#      DATABASE_URL: postgres://user:password@main-db:5432/main
#      REDIS_HOST: redis
#      NATS_URL: nats://nats:4222
#    depends_on:
#      - main-db
#      - redis
#      - nats
#
#  web:
#    build:
#      context: ../apps/web/enchere-et-en-os
#      dockerfile: ../../../docker/Dockerfile.web
#    ports:
#      - "3000:3000"

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  main-db:
    image: postgres:17.5
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: main
    volumes:
      - main-db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  keycloak:
    image: quay.io/keycloak/keycloak:26.2.1
    command: start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: user
      KC_DB_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    volumes:
      - ./realm-export.json:/opt/keycloak/data/import/realm-export.json

  keycloak-db:
    image: postgres:17.5
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-data:/var/lib/postgresql/data

  nats:
    image: nats:2.10
    ports:
      - "4222:4222"  # client
      - "8222:8222"  # monitoring

volumes:
  main-db-data:
  keycloak-data:
