name: CI/CD - Deploy to Production

on:
  push:
    branches:
      - 38-optimize-cicd-and-deployment

jobs:
  lint-test-services:
    name: Lint & Test - Services
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 23.6.0
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm verify

  build-and-deploy:
    name: Build & Deploy to Production
    runs-on: ubuntu-latest
    needs:
      - lint-test-services
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose -f docker/docker-compose.prod.yml build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /var/www/enchere-et-en-os
            git pull
            cd docker
            docker compose --env-file .env.prod -f docker-compose.prod.yml down
            docker compose --env-file .env.prod -f docker-compose.prod.yml up -d --build