name: CI/CD - Deploy to Production

on:
  push:
    branches:
      - 22-setup-cicd-github-workflow

jobs:
  lint-test-auction:
    name: Lint & Test - Auction Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 23.6.0
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm --filter "auction-service..." lint
      - run: pnpm --filter "auction-service..." test

  lint-test-product:
    name: Lint & Test - Product Service
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 23.6.0
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm --filter "product-service..." lint
      - run: pnpm --filter "product-service..." test

  lint-test-web:
    name: Lint & Test - Web (Next.js)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: 23.6.0
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm --filter "enchere-et-en-os..." lint
      - run: pnpm --filter "enchere-et-en-os..." test

  build-and-deploy:
    name: Build & Deploy to Production
    runs-on: ubuntu-latest
    needs:
      - lint-test-auction
      - lint-test-product
      - lint-test-web
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose -f docker-compose.prod.yml build

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.PROD_HOST }}
          username: ${{ secrets.PROD_USER }}
          key: ${{ secrets.PROD_SSH_KEY }}
          script: |
            cd /home/enchere/production
            git pull origin main
            export POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            export POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            export KEYCLOAK_ADMIN=${{ secrets.KEYCLOAK_ADMIN }}
            export KEYCLOAK_ADMIN_PASSWORD=${{ secrets.KEYCLOAK_ADMIN_PASSWORD }}
            docker compose -f docker-compose.prod.yml down
            docker compose -f docker-compose.prod.yml up -d --build